name: Deploy v3 Pools Subgraphs
on:
  push:
    branches: main
    paths:
      - "subgraphs/v3-pools/**"
  workflow_dispatch:

jobs:
  deploy-mainnet:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: mainnet
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}

  deploy-gnosis:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: gnosis
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}

  deploy-sepolia:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: sepolia
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}

  deploy-arbitrum:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: arbitrum-one
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}

  deploy-base:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: base
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}

  deploy-sonic:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: sonic
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}

  deploy-avalanche:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: avalanche
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}

  deploy-optimism:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: optimism
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}

  deploy-xlayer:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: xlayer
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}

  deploy-plasma:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: plasma
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}

  deploy-hyperevm:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: hyperevm
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}

  deploy-monad:
    uses: ./.github/workflows/deploy-ormi.yml
    with:
      subgraph: pools
      network: monad
    secrets:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}
