name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      subgraph:
        description: "Choose subgraph"
        required: true
        default: "vault"
        type: choice
        options:
          - vault
          - pools
      network:
        description: "Choose network"
        required: true
        default: "mainnet"
        type: choice
        options:
          - mainnet
          - gnosis
          - sepolia
          - arbitrum-one
          - base
          - sonic
          - avalanche
          - optimism
          - hyperevm
          - plasma
          - xlayer
          - monad

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: graph
    env:
      DEPLOY_KEY: ${{ secrets.ORMI_DEPLOY_KEY }}
      NETWORK: ${{ inputs.network }}
      SUBGRAPH: ${{ inputs.subgraph }}
    steps:
      - uses: actions/checkout@v6

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install
        run: pnpm install

      - name: Generate manifests
        id: generate-manifests
        run: pnpm generate-manifests

      - name: Graph Codegen
        id: graph-codegen
        working-directory: ./subgraphs/v3-vault
        run: pnpm codegen subgraph.sepolia.yaml

      - name: Graph Build
        id: graph-build
        working-directory: ./subgraphs/v3-vault
        run: pnpm build

      - name: Deploy
        run: |
          sh script/deploy.sh v3-"$SUBGRAPH" "$NETWORK"
